#!/bin/bash

echo "Complie the java source code..."
echo "Java Classpath: "
echo $CLASSPATH
javac *.java
echo "Complie is done!"
echo "Move the class to the tomcat..."
mv *.class /usr/local/tomcat/webapps/ROOT/WEB-INF/classes
echo "Move is done!"
echo "Copy the htm files to tomcat..."
cp *.htm /usr/local/tomcat/webapps/ROOT
echo "Copy is done!"

echo ""
echo "Show tomcat logs======================================================================================================"
tail -f /usr/local/tomcat/logs/catalina.out
